### ISSUE TITLE
SslConfigs SSL_PROTOCOL_CONFIG wrong value

### ISSUE THREAD

**Issue by stomashchuk** [a0x8o/kafka#33]
SSL_PROTOCOL_CONFIG property in class SslConfigs has value "ssl.protocol". But for ssl connection to kafka we need to use "security.protocol" value.

**Comment by OneCricketeer** [comment]
Please use JIRA to report Kafka project issues 

https://issues.apache.org/jira/browse/KAFKA

**Comment by OneCricketeer** [comment]
Besides, you're using the wrong config class

https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/CommonClientConfigs.java#L99

**Comment by stomashchuk** [comment]
Hi Jordan. Thank you for your reply. Ok, sorry. Apparently I didn't pay enough attention to reading documentation. Could I ask one question - why don't class, that you mentioned, contains truststore, keystore parameters?

**Comment by stomashchuk** [comment]
Thank you very much for your answers. Good luck )
